version: '3'

services:
  digitai_api:
    build:
      context: ./digitai_api
    env_file:
      - .env
    ports:
      - "8000:8000"

  digitai_frontend:
    build:
      context: ./digitai_frontend
    env_file:
      - .env
    depends_on:
      - digitai_api
    ports:
      - "8501:8501"